recipe: default.v1
language: ar
pipeline:
  - name: LLMCommandGenerator
    llm:
      type: "openai"
      model_name: gpt-4o
      temperature: 0.0
      max_tokens: 1000
    embeddings:
        model_name: "text-embedding-ada-002"
    flow_retrieval:
      embeddings:
        type: openai
        model: text-embedding-ada-002
policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  prompt: rag.jinja2
  vector_store:
    type: "faiss"
    source: "docs"
#  - name: RulePolicy
assistant_id: 20240806-152647-regular-simulcast
